name: iOS Build
on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Build for iOS Simulator
        run: ./gradlew :composeApp:iosX64Binaries 
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-simulator
          path: composeApp/build/bin/iosX64/debugExe/ 
